
# This image comes with:
# - ubuntu:focal (what IA infrastructure runs circa 2021)
# - python3.11 dev setup (via deadsnakes)
image: "vilmibm/scholar-test-base:focal"

variables:
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"

test_python:
  script:
    - python3.11 -mvenv .venv
    - .venv/bin/pip install -rci.requirements.txt
    - make lint
    - make test
