
# This image comes with:
# - ubuntu:jammy
# - python3 dev setup
# - pipenv
image: "bnewbold/fatcat-test-base:jammy"

before_script:
  - pipenv --version

variables:
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"
  PIPENV_VENV_IN_PROJECT: "true"

test_python:
  script:
    - pipenv install --dev --deploy
    - make test
    - make lint
